/*
 * ceracoder (https://github.com/CERALIVE/ceracoder): the Ceracoder encoder and its
 * bitrate-control parameters (validation of UI updates, the INI config).
 *
 * When ENCODER_BIN points at ceracoder instead of belacoder, the encoder takes
 * its bitrate settings from a config file (-c) rather than the legacy bitrate
 * file (-b), and re-reads it on SIGHUP:
 *
 *   [general]
 *   min_bitrate = 500     # Kbps
 *   max_bitrate = 6000    # Kbps
 *   balancer = adaptive   # adaptive | fixed | aimd
 *
 *   [srt]
 *   latency = 2000        # ms
 *
 *   [adaptive]  incr_step / decr_step (Kbps), incr_interval / decr_interval (ms)
 *   [aimd]      incr_step (Kbps), decr_mult (0-1), incr_interval / decr_interval (ms)
 *
 * Max bitrate and SRT latency live in the encoder config (belacoder uses the
 * same values), everything else in the persisted `ceracoder` section.
 */
import { CERACODER_CONF } from "../config";
import { Encoder } from "../encoder";
import { saveState, state } from "../state";
import { BITRATE_KBPS } from "../validate";

export const CERA_BALANCERS = ["adaptive", "fixed", "aimd"] as const;
export type CeraBalancer = (typeof CERA_BALANCERS)[number];

/** Tuning of the adaptive (default) balancer. */
export interface AdaptiveTuning {
	incrStep: number;      // Kbps
	decrStep: number;      // Kbps
	incrInterval: number;  // ms
	decrInterval: number;  // ms
}

/** Tuning of the AIMD balancer. */
export interface AimdTuning {
	incrStep: number;      // Kbps
	decrMult: number;      // fraction of the bitrate kept on congestion (0-1)
	incrInterval: number;  // ms
	decrInterval: number;  // ms
}

/** ceracoder parameters persisted in the device config (`ceracoder` section). */
export interface CeraConfig {
	balancer: CeraBalancer;
	minBitrate: number;    // Kbps
	adaptive: AdaptiveTuning;
	aimd: AimdTuning;
}

export const DEFAULT_CERA_CONFIG: CeraConfig = {
	balancer: "adaptive",
	minBitrate: 500,
	adaptive: { incrStep: 30, decrStep: 100, incrInterval: 500, decrInterval: 200 },
	aimd: { incrStep: 50, decrMult: 0.75, incrInterval: 500, decrInterval: 200 },
};

type Range = readonly [min: number, max: number];
const STEP: Range = [1, 10_000];
const INTERVAL: Range = [10, 60_000];
/** Integer bounds per tuning field; `null` marks aimd.decrMult, a fraction in (0, 1). */
const TUNING_RANGES = {
	adaptive: { incrStep: STEP, decrStep: STEP, incrInterval: INTERVAL, decrInterval: INTERVAL },
	aimd: { incrStep: STEP, decrMult: null, incrInterval: INTERVAL, decrInterval: INTERVAL },
} as const;

function intInRange(value: unknown, key: string, [min, max]: Range): number {
	const n = Number(value);
	if (!Number.isInteger(n) || n < min || n > max) {
		throw new Error(`${key} must be an integer between ${min} and ${max}`);
	}
	return n;
}

/**
 * Validate and merge a partial update (as sent by the UI) over the current
 * settings; returns the complete new config. Throws on invalid values.
 */
function mergeCeraConfig(current: CeraConfig, partial: unknown): CeraConfig {
	const p = (partial && typeof partial === "object" ? partial : {}) as Record<string, unknown>;
	if (p.balancer != null && !CERA_BALANCERS.includes(p.balancer as CeraBalancer)) {
		throw new Error(`Invalid balancer: ${String(p.balancer)}`);
	}
	const merged: CeraConfig = {
		balancer: (p.balancer as CeraBalancer | undefined) ?? current.balancer,
		minBitrate: p.minBitrate == null
			? current.minBitrate
			: intInRange(p.minBitrate, "minBitrate", [BITRATE_KBPS.min, BITRATE_KBPS.max]),
		adaptive: { ...current.adaptive },
		aimd: { ...current.aimd },
	};

	for (const group of ["adaptive", "aimd"] as const) {
		const update = p[group];
		if (update == null) continue;
		if (typeof update !== "object") throw new Error(`${group} must be an object`);
		const target = merged[group] as unknown as Record<string, number>;
		for (const [key, range] of Object.entries(TUNING_RANGES[group])) {
			const value = (update as Record<string, unknown>)[key];
			const name = `${group}.${key}`;
			if (range) {
				if (value !== undefined) target[key] = intInRange(value, name, range);
				continue;
			}
			const n = value === undefined ? target[key] : Number(value);
			if (!Number.isFinite(n) || n <= 0 || n >= 1) {
				throw new Error(`${name} must be a number between 0 and 1 (exclusive)`);
			}
			target[key] = n;
		}
	}
	return merged;
}

/** Render the INI config as ceracoder's -c flag consumes it. */
function ceraConfText(cfg: CeraConfig, maxBitrate: number, latency: number): string {
	const section = (name: string, values: Record<string, number | string>) =>
		[`[${name}]`, ...Object.entries(values).map(([k, v]) => `${k} = ${v}`), ""];
	// Fixed key order (the persisted config sorts keys alphabetically)
	const tuning = (group: "adaptive" | "aimd") =>
		Object.fromEntries(Object.keys(TUNING_RANGES[group]).map((k) => [
			k.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`),
			(cfg[group] as unknown as Record<string, number>)[k],
		]));
	return [
		"# Generated by belabox-duo — do not hand-edit (use the control UI)",
		"",
		...section("general", { min_bitrate: cfg.minBitrate, max_bitrate: maxBitrate, balancer: cfg.balancer }),
		...section("srt", { latency }),
		...section("adaptive", tuning("adaptive")),
		...section("aimd", tuning("aimd")),
	].join("\n");
}

export class Ceracoder extends Encoder {
	/** Bitrate-control settings as persisted in the device state (defaults applied). */
	config(): CeraConfig {
		return state.ceracoder ?? DEFAULT_CERA_CONFIG;
	}

	/** Validate and persist a partial settings update, rewrite the INI and reload a running encoder. */
	async update(partial: unknown): Promise<CeraConfig> {
		const next = mergeCeraConfig(this.config(), partial);
		state.ceracoder = next;
		await this.writeBitrateControl(next.minBitrate, state.encoder.config?.maxBitrate ?? 5000);
		this.reload();
		await saveState();
		return next;
	}

	override setBitrate(minKbps: number, maxKbps: number) {
		// The INI reads the min from the persisted ceracoder section; keep it in sync
		state.ceracoder = { ...this.config(), minBitrate: minKbps };
		return super.setBitrate(minKbps, maxKbps);
	}

	protected bitrateArgs(): string[] {
		return ["-c", CERACODER_CONF];
	}

	/** The min comes from the ceracoder section, the latency from the encoder config. */
	protected writeBitrateControl(_minKbps: number, maxKbps: number): Promise<void> {
		const latency = state.encoder.config?.latency ?? 2000;
		return this.writeControlFile(CERACODER_CONF, ceraConfText(this.config(), maxKbps, latency));
	}
}
