// REFACTOR-modules.md §4.1 — build-time generated frontend module manifest.
//
// Scans modules/*/frontend.tsx and emits modules/.generated.frontend.ts: one
// static import per module (sorted for deterministic output), default-exporting
// the registrations as an array. This file lists paths only — it never imports
// a module — so a broken module cannot break the generator, and the browser
// bundle statically resolves every import (no runtime Glob).
//
// Runs in Bun (not the browser) and is re-invoked by server.ts before it
// bundles the web UI, plus by package.json `predev`/`prebuild`. Regenerated on
// demand; only rewrites the file when the output actually changes so watch
// loops don't churn it.
import { fileURLToPath } from "node:url";
import { writeFile, readFile } from "node:fs/promises";
import { sep } from "node:path";

// scripts/ lives next to modules/ — the app dir is the scan base so the
// relative pattern below resolves the same way regardless of the CWD.
const baseDir = fileURLToPath(new URL("..", import.meta.url));
const outFile = fileURLToPath(new URL("../modules/.generated.frontend.ts", import.meta.url));

const matches: string[] = [];
for await (const p of new Bun.Glob("modules/*/frontend.tsx").scan({ cwd: baseDir })) matches.push(p);
matches.sort();

const lines = [
	"// AUTO-GENERATED by scripts/gen-modules.ts — do not edit.",
	"// REFACTOR-modules.md §4.1: one static import per modules/<id>/frontend.tsx,",
	"// in sorted path order; the browser bundle never uses Glob.",
	"",
];

matches.forEach((path, i) => {
	// path = <modulesDir>/<id>/frontend.tsx  →  import "./<id>/frontend"
	const id = path.split(sep);
	const moduleId = id[id.length - 2];
	lines.push(`import m${i} from "./${moduleId}/frontend";`);
});

lines.push("");
lines.push(
	matches.length
		? `export default [${[...Array(matches.length)].map((_, i) => `m${i}`).join(", ")}] as unknown[];`
		: "export default [] as unknown[];",
	"",
);

const next = lines.join("\n");
let prev = "";
try {
	prev = await readFile(outFile, "utf8");
} catch {
	/* missing — will write */
}
if (next !== prev) await writeFile(outFile, next);
console.log(`[gen-modules] modules/.generated.frontend.ts → ${matches.length} frontend module(s)`);
